version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: togo-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/output:/app/output
    environment:
      - GIN_MODE=release
    networks:
      - togo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://101.126.6.243/api
        - VITE_STATIC_BASE_URL=http://101.126.6.243/static
    container_name: togo-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - togo-network

networks:
  togo-network:
    driver: bridge

volumes:
  uploads_data:
  output_data:
