version: '3.8'
services:
  backend:
    build: ./backend
    container_name: togo-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.production
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/output:/app/output
      - ./backend/logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - togo-net

  frontend:
    build: 
      context: ./frontend
      args:
        - NODE_ENV=production
    container_name: togo-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - togo-net

  nginx:
    image: nginx:latest
    container_name: togo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - togo-net

networks:
  togo-net:
    driver: bridge
